apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: microservices
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::347277718217:role/pix-banking-system-dev-auth-service-sa-role