# Network Policy - Settlement Service
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: settlement-service-netpol
  namespace: pix-microservices
spec:
  podSelector:
    matchLabels:
      app: settlement-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: pix-microservices
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443   # AWS APIs (DynamoDB, SNS, SQS)