apiVersion: v1
kind: ServiceAccount
metadata:
  name: settlement-service
  namespace: pix-microservices
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::347277718217:role/pix-banking-system-dev-settlement-service-sa-role