# Auth Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: microservices
type: Opaque
stringData:
  jwt_secret: "pix-banking-jwt-secret-2025-change-in-production-abc123xyz789"
  jwt_refresh_secret: "pix-banking-refresh-secret-2025-change-in-production-def456uvw012"