apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: microservices
type: Opaque
stringData:
  jwt_secret: "I9Clfol7zwO85INdwgkUhQlyEZBD3dS9m7nLZVeHv/0="
  jwt_refresh_secret: "QCxZyE8MOZZUWq1OpHgdY0FgitgJvRlfJ6xhjlkAnhs="
